name: Deploy .NET Lambda to AWS

on:
  push:
    branches:
      - release
  workflow_dispatch:

env:
  # Updated ARN
  LAMBDA_FUNCTION_ARN: arn:aws:lambda:us-east-1:211635102441:function:tender-tool-sync-stack-AspNetCoreFunction-dO4NR72ycKCm

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        # Pinned to a specific commit SHA
        uses: actions/checkout@a5ac7e51b4109f5124f2601c3e7b5f8e0539113f

      - name: Set up .NET 8
        # Pinned to a specific commit SHA
        uses: actions/setup-dotnet@B59B622E1A11F5EA95A591B1A736B461168B52B8
        with:
          dotnet-version: '8.0'

      - name: Install AWS Lambda Tools
        run: dotnet tool install -g Amazon.Lambda.Tools

      - name: Build and Package Lambda
        run: |
          # Updated project file name
          dotnet lambda package -c Release -o ./lambda.zip TenderToolSyncLambda.csproj

      - name: Configure AWS credentials
        # Pinned to a specific commit SHA
        uses: aws-actions/configure-aws-credentials@b0c66bce8b23e8d0800b65a3978b31d0c5a6100f
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }} 

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name ${{ env.LAMBDA_FUNCTION_ARN }} \
            --zip-file fileb://lambda.zip
